
[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[font]
size = 12.0
normal = { family = "JetBrains Mono Nerd Font Mono", style = "Regular" }

[cursor]
style = { shape = "Beam", blinking = "Never" }

[window]
startup_mode = "Maximized"

[general]
import = [
	"~/.config/alacritty/catppuccin_mocha.toml"
]

[terminal]
